name: Jekyll Themes
# url: https://julymars.github.io/jekyllthemes
baseurl: /
description: Insert tagline here

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: rouge
paginate: 20

rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
